### ISSUE TITLE
Fix x86_64 windows (wac) functionality

### ISSUE THREAD

**Issue by silentbugs** [silentbugs/hon-client-scraper#4] opened 2022-04-07 13:14 UTC
It seems like the x86_64 version is hosted on a different endpoint.

**Comment by mrhappyasthma** [comment] 2022-04-07 17:03
This is a duplicate of https://github.com/silentbugs/hon-client-scraper/issues/1

**Comment by silentbugs** [comment] 2022-04-13 00:21
Closing since this is a duplicate of #1.

**Closed as completed** 2022-04-13 00:21 UTC
